version: '3.8'

services:
  app:
    build: .
    ports:
      - "4355:4355"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/faceswap
      - REPLICATE_API_KEY=${REPLICATE_API_KEY}
      - REPLICATE_VERSION=${REPLICATE_VERSION}
    volumes:
      - ./public:/app/public
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: