version: '2'

services:
  faceswap:
    image: erkansivas/faceswap
    ports:
      - "8080:80"
      - "4355:4355"
    volumes:
      - ./public:/app/public
    restart: unless-stopped
    networks:
      - faceswap_network

networks:
  faceswap_network:
    name: faceswap_network