name: Deploy to Production

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/faceswap:latest
          build-args: |
            MONGODBURI=${{ secrets.MONGODBURI }}
            UPLOADS_BASE_URL=https://face-swap-api.erkansivas.xyz/uploads/
            REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }}
            REPLICATE_VERSION=${{ secrets.REPLICATE_VERSION }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/erkan/docker-projects/faceswap
            rm -rf docker-compose.yml
            curl -o docker-compose.yml https://raw.githubusercontent.com/erkansivas35/face-swap-ai-api/refs/heads/dev/docker-compose.yml
            echo "MONGODBURI=${{ secrets.MONGODBURI }}" > .env
            echo "UPLOADS_BASE_URL=https://face-swap-api.erkansivas.xyz/uploads/" >> .env
            echo "REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }}" >> .env
            echo "REPLICATE_VERSION=${{ secrets.REPLICATE_VERSION }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            docker-compose down
            docker-compose pull
            docker-compose up -d
