name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/faceswap:latest
          build-args: |
            REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }}
            REPLICATE_VERSION=${{ secrets.REPLICATE_VERSION }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            cd /home/erkan/docker-projects/faceswap
            echo "REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }}" > .env
            echo "REPLICATE_VERSION=${{ secrets.REPLICATE_VERSION }}" >> .env
            docker-compose pull
            docker-compose up -d